# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e599e18ce4bb6666d11d583518137231a45eb9e15c4206efc778803109c610c0b81c8a0369abb2360db4dfb0ccbad464dd73f706777e0695728224bac21bda7

test:
  secret_key_base: 75153a42eb797629206f513576fb9bc75a8326cf943114bc2ad8c6357644ac75a5331f8b23a7ff4f88232ab306900aa62ca5be6587ff39c50cbcfedc22c07968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
